### PR TITLE
Merge 'master' branch of 'redox-os/termion' into 'windows' branch

### PR DESCRIPTION
**Pull request by agavrilov**
Our company is using termion on Linux and macOS to create command-line utilies. Now we are interested in Windows port of these utilies. I'll try to push your Windows of termion as much as I can if you don't mind

### CODE REVIEW

**Comment by ErichDonGubler** [comment]
This is currently failing CI -- could we please get the Linux/MacOS builds working before this gets merged? I'm assuming upstream is green, but I'm on mobile right now and can't easily check.

**Comment by ErichDonGubler** [comment]
Also, welcome! Thanks for taking the time to make a PR! I don't consider myself the exclusive owner of these Windows changes, so if you wanted to fork upstream and run with them you'll have no complaints from me. :)

**Comment by agavrilov** [comment]
I have added Windows test environment for Travis. It uses MSYS as a shell and Windows tests are failing on it. I commented out these failing Windows tests until I have time to fix them

**Comment by ErichDonGubler** [comment]
Awesome! Thank you. :) Merging!

Just so you know: my wife had a baby two days ago right about when you submitted this PR...if it weren't for that, I definitely would have merged this earlier!

**Comment by agavrilov** [comment]
Congratulations on a new baby!

**Pull request merged**
